/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseAccordion: typeof import('./../components/ui/BaseAccordion.vue')['default']
    BaseButton: typeof import('./../components/ui/BaseButton.vue')['default']
    BaseSegmented: typeof import('./../components/ui/BaseSegmented.vue')['default']
    BaseTag: typeof import('./../components/ui/BaseTag.vue')['default']
    ForgeLogo: typeof import('./../components/ui/ForgeLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./../components/ui/SectionHeader.vue')['default']
  }
}
